<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.dpdns.sazenice</groupId>
    <artifactId>fakedeathban</artifactId>
    <version>1.11-pre5</version>
    <packaging>jar</packaging>

    <name>fakedeathban</name>

    <properties>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Default Minecraft version -->
        <spigot.version>26.3-R0.1-SNAPSHOT</spigot.version>
        <minecraft.version>26.3</minecraft.version>
    </properties>

    <build>
        <defaultGoal>clean package</defaultGoal>

        <finalName>${project.artifactId}-${project.version}-mc${minecraft.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.3</version>
                <configuration>
                    <createDependencyReducedPom>false</createDependencyReducedPom>

                    <relocations>
                        <relocation>
                            <pattern>org.bstats</pattern>
                            <shadedPattern>org.dpdns.sazenice</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <profiles>
        <profile>
            <id>mc-1.21.11</id>

            <properties>
                <minecraft.version>1.21.11</minecraft.version>
                <spigot.version>1.21.11-R0.2-SNAPSHOT</spigot.version>
            </properties>
        </profile>
        <profile>
            <id>mc-26.1.1</id>

            <properties>
                <minecraft.version>26.1.1</minecraft.version>
                <spigot.version>26.1.1-R0.1-SNAPSHOT</spigot.version>
            </properties>
        </profile>
        <profile>
            <id>mc-26.1.2</id>

            <properties>
                <minecraft.version>26.1.2</minecraft.version>
                <spigot.version>26.1.2-R0.1-SNAPSHOT</spigot.version>
            </properties>
        </profile>
        <profile>
            <id>mc-26.2</id>

            <properties>
                <minecraft.version>26.2</minecraft.version>
                <spigot.version>26.2-R0.1-SNAPSHOT</spigot.version>
            </properties>
        </profile>
        <profile>
            <id>mc-26.3</id>

            <properties>
                <minecraft.version>26.3</minecraft.version>
                <spigot.version>26.3-R0.1-SNAPSHOT</spigot.version>
            </properties>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>${spigot.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.2.1</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
