deathbanned: []
frozen: []

default-spectator: "PandakYT"
default-gamemode: "ADVENTURE"
death-sound: "minecraft:entity.wither.spawn"
revive-sound: "minecraft:block.beacon.activate"
config-version: "1.9-pre2"

language: "en_us"