name: FakeDeathBan
version: 1.11-pre5
load: STARTUP
main: org.dpdns.sazenice.fakeDeathBan.FakeDeathBan
api-version: 1.21
author: sazenice
website: https://sazenice.dpdns.org
description: "A deathban plugin that allows players to stay connected to the server after a deathban"

commands:
  revive:
    description: "Revives and teleports all players to you"
    usage: /<command> [player...]
    aliases:
      - udb
      - undeathban
      - res
      - rev
    permission: fakedeathban.revive
  defaultspectate:
    description: "Sets the default spectator"
    usage: /<command> <player>
    aliases:
      - defspectate
      - defspec
      - defs
    permission: fakedeathban.defaultspectate
  spectate:
    description: "Spectates a player"
    usage: /<command> <player>
    aliases:
      - spec
      - s
    permission: fakedeathban.spectate
  freezebanned:
    description: "Freezes a player"
    usage: /<command> [player...]
    aliases:
      - fb
      - freezeb
      - fbanned
      - fr
    permission: fakedeathban.freezebanned
  defaultgamemode:
    description: "Sets the default gamemode after a revive"
    usage: /<command> <gamemode>
    aliases:
      - defg
      - dgamemode
      - defaultg
      - dg
    permission: fakedeathban.defaultgamemode
  unfreezebanned:
    description: "Unfreezes a player"
    usage: /<command> [player...]
    aliases:
      - unfreezeb
      - unfbanned
      - ufb
      - unfrb
    permission: fakedeathban.unfreezebanned
  setsound:
    description: "Sets the sound after a death/revive"
    usage: /<command> <death|revive> <sound>
    permission: fakedeathban.setsound
  immortality:
    description: "Sets the immortality mode"
    usage: /<command>
    permission: fakedeathban.immortality
  setimmunity:
    description: "Adds immunity to a player"
    usage: /<command> <player> <immunity>
    permission: fakedeathban.setimmunity
    aliases:
      - setimmune
      - setim
      - simmune
      - sim
  togglefdb:
    description: "Turns listeners on or off"
    usage: /<command>
    permission: fakedeathban.togglefdb
  fdbui:
    description: "Shows a GUI for FakeDeathBan"
    usage: /<command>
    permission: fakedeathban.fdbui
    aliases:
      - menu
      - open
  fdblist:
    description: "Shows deathbanned players"
    usage: /<command>
    permission: fakedeathban.fdblist
  simulateban:
    description: "Fakes a player ban"
    usage: /<command> <player> <message>
    permission: fakedeathban.simulateban
    aliases:
      - simb
      - simban
      - fakeb
      - fakeban
permissions:
  # Command permissions
  fakedeathban.revive:
    default: op
  fakedeathban.defaultspectate:
    default: op
  fakedeathban.spectate:
    default: true
  fakedeathban.freezebanned:
    default: op
  fakedeathban.defaultgamemode:
    default: op
  fakedeathban.unfreezebanned:
    default: op
  fakedeathban.setsound:
    default: op
  fakedeathban.immortality:
    default: op
  fakedeathban.setimmunity:
    default: op
  fakedeathban.togglefdb:
    default: op
  fakedeathban.fdbui:
    default: op
  fakedeathban.fdblist:
    default: op
  fakedeathban.simulateban:
    default: op
  # Immunity permissions
  fakedeathban.bypass.deathban:
    description: Immunity against DeathBan
    default: false
  fakedeathban.bypass.freeze:
    description: Immunity against freezes
    default: false
  fakedeathban.bypass.joinquit:
    description: Immunity for Join/Quit messages
    default: false
  fakedeathban.bypass.move:
    description: Immunity for movement
    default: false
  fakedeathban.bypass.immortality:
    description: Immunity against immortality mode
    default: false