name: FakeDeathBan
version: 1.7-pre-4
load: POSTWORLD
main: cz.sk.corrupted.universe.fakeDeathBan.FakeDeathBan
api-version: 1.21
author: sazenice
website: https://github.com/sazenice/FakeDeathBan
commands:
  undeathban:
    description: "Teleportuje všechny hráče s death banem k tobě a odstraní jim deathban"
    usage: /<command> [hráč...]
    aliases:
      - udb
      - undb
      - udban
      - udeathb
      - undeathb
      - undban
      - udeathban
    permission: fakedeathban.undeathban
  setspectate:
    description: "Nastaví hráče, který se bude spectatovat když někdo má deathban"
    usage: /<command> <hráč>
    aliases:
      - sets
      - setspec
      - sspec
      - ss
    permission: fakedeathban.setspectate
  spectate:
    description: "Nastaví hráče, který se bude spectatovat když ty máš deathban"
    usage: /<command> <hráč>
    aliases:
      - spec
      - s
    permission: fakedeathban.freeze
  freeze:
    description: "Zmrazí všechny hráče, co mají deathban"
    usage: /<command> [hráč...]
    aliases:
      - fr
    permission: fakedeathban.freeze
  defg:
    description: "Nastaví výchozí gamemode pro hráče, kterým se odstraní deathban"
    usage: /<command> <gamemode>
    aliases:
      - defaultgamemode
      - dgamemode
      - defaultg
      - dg
    permission: fakedeathban.defg
  unfreeze:
    description: "Rozmrazí všechny hráče, co jsou zmraženi"
    usage: /<command> [hráč...]
    aliases:
      - unfr
    permission: fakedeathban.unfreeze
  version:
    description: "Ukáže informace o pluginu"
    usage: /<command>
    permission: fakedeathban.version
  check:
    description: "Zjistí, zda všechny proměné, co mají být v config.yml existují"
    usage: /<command>
    aliases:
      - health
      - chk
    permission: fakedeathban.check
  setsound:
    description: "Nastaví zvuk když někdo umře nebo se oživí"
    usage: /<command> <death|revive> <sound>
    permission: fakedeathban.setsound
permissions:
  fakedeathban.undeathban:
    default: op
  fakedeathban.setspectate:
    default: op
  fakedeathban.spectate:
    default: true
  fakedeathban.freeze:
    default: op
  fakedeathban.defg:
    default: op
  fakedeathban.unfreeze:
    default: op
  fakedeathban.version:
    default: true
  fakedeathban.check:
    default: true
  fakedeathban.setsound:
    default: op